version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - PhantomMatthew
    labels:
      - dependencies
      - rust

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    reviewers:
      - PhantomMatthew
    labels:
      - dependencies
      - github-actions
