//! Chat completion tool for LLM-based tasks
//!
//! Provides capabilities for:
//! - Text generation
//! - Chat completion
//! - Summarization
//! - Translation

use crate::context::Context;
use crate::tool::{Tool, ToolError, ToolParameter, ToolResult, ToolSchema};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Chat message role
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum MessageRole {
    System,
    User,
    Assistant,
}

/// Chat message
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Message role
    pub role: MessageRole,
    /// Message content
    pub content: String,
}

/// Chat completion input
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionInput {
    /// Conversation messages
    pub messages: Vec<ChatMessage>,
    /// Model to use (optional)
    #[serde(default)]
    pub model: Option<String>,
    /// Temperature (0.0 - 2.0)
    #[serde(default = "default_temperature")]
    pub temperature: f32,
    /// Maximum tokens to generate
    #[serde(default = "default_max_tokens")]
    pub max_tokens: usize,
    /// Top-p sampling
    #[serde(default = "default_top_p")]
    pub top_p: f32,
    /// Stop sequences
    #[serde(default)]
    pub stop: Option<Vec<String>>,
}

fn default_temperature() -> f32 { 0.7 }
fn default_max_tokens() -> usize { 1024 }
fn default_top_p() -> f32 { 1.0 }

/// Chat completion response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionResponse {
    /// Generated content
    pub content: String,
    /// Model used
    pub model: String,
    /// Token usage
    pub usage: TokenUsage,
}

/// Token usage statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenUsage {
    pub prompt_tokens: usize,
    pub completion_tokens: usize,
    pub total_tokens: usize,
}

/// Chat completion tool
pub struct ChatCompletionTool {
    default_model: String,
}

impl ChatCompletionTool {
    /// Create a new chat completion tool
    pub fn new() -> Self {
        Self {
            default_model: "gpt-4".to_string(),
        }
    }

    /// Create with custom default model
    pub fn with_model(model: &str) -> Self {
        Self {
            default_model: model.to_string(),
        }
    }

    /// Estimate token count (rough approximation)
    fn estimate_tokens(text: &str) -> usize {
        // Rough estimate: ~4 characters per token for English
        text.len() / 4 + 1
    }

    /// Simulate chat completion
    /// In a real implementation, this would call an LLM API
    async fn complete(&self, input: &ChatCompletionInput) -> Result<ChatCompletionResponse, ToolError> {
        let model = input.model.clone().unwrap_or_else(|| self.default_model.clone());

        // Build prompt from messages
        let prompt_tokens: usize = input
            .messages
            .iter()
            .map(|m| Self::estimate_tokens(&m.content))
            .sum();

        // In a real implementation, this would call the LLM API
        // For now, return a stub response based on the last user message
        let last_user_msg = input
            .messages
            .iter()
            .rev()
            .find(|m| m.role == MessageRole::User)
            .map(|m| m.content.as_str())
            .unwrap_or("Hello");

        let response_content = format!(
            "[Stub response from {}] I received your message: '{}'. \
             In a real implementation, this would be generated by an LLM.",
            model,
            if last_user_msg.len() > 50 {
                &last_user_msg[..50]
            } else {
                last_user_msg
            }
        );

        tracing::info!(
            "Chat completion requested with {} messages, model: {}",
            input.messages.len(),
            model
        );

        Ok(ChatCompletionResponse {
            content: response_content.clone(),
            model,
            usage: TokenUsage {
                prompt_tokens,
                completion_tokens: Self::estimate_tokens(&response_content),
                total_tokens: prompt_tokens + Self::estimate_tokens(&response_content),
            },
        })
    }

    /// Format the response for output
    fn format_response(response: &ChatCompletionResponse) -> String {
        let mut output = String::new();

        output.push_str("## Chat Completion Result\n\n");
        output.push_str(&format!("**Model:** {}\n\n", response.model));
        output.push_str("**Response:**\n");
        output.push_str(&response.content);
        output.push_str("\n\n");
        output.push_str(&format!(
            "**Tokens:** {} prompt + {} completion = {} total\n",
            response.usage.prompt_tokens,
            response.usage.completion_tokens,
            response.usage.total_tokens
        ));

        output
    }
}

impl Default for ChatCompletionTool {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Tool for ChatCompletionTool {
    fn name(&self) -> &'static str {
        "chat_completion"
    }

    fn description(&self) -> &'static str {
        "LLM chat completion tool for text generation, summarization, and conversation"
    }

    fn parameters(&self) -> Option<ToolSchema> {
        Some(ToolSchema {
            schema_type: "object".to_string(),
            properties: {
                let mut props = HashMap::new();
                props.insert(
                    "messages".to_string(),
                    ToolParameter {
                        name: "messages".to_string(),
                        param_type: "array".to_string(),
                        description: Some("Array of chat messages with role and content".to_string()),
                        required: Some(true),
                        default: None,
                        enum_values: None,
                    },
                );
                props.insert(
                    "model".to_string(),
                    ToolParameter {
                        name: "model".to_string(),
                        param_type: "string".to_string(),
                        description: Some("Model to use (e.g., 'gpt-4', 'claude-3-opus')".to_string()),
                        required: Some(false),
                        default: None,
                        enum_values: None,
                    },
                );
                props.insert(
                    "temperature".to_string(),
                    ToolParameter {
                        name: "temperature".to_string(),
                        param_type: "number".to_string(),
                        description: Some("Sampling temperature (0.0-2.0, default: 0.7)".to_string()),
                        required: Some(false),
                        default: Some(serde_json::json!(0.7)),
                        enum_values: None,
                    },
                );
                props.insert(
                    "max_tokens".to_string(),
                    ToolParameter {
                        name: "max_tokens".to_string(),
                        param_type: "integer".to_string(),
                        description: Some("Maximum tokens to generate (default: 1024)".to_string()),
                        required: Some(false),
                        default: Some(serde_json::json!(1024)),
                        enum_values: None,
                    },
                );
                props.insert(
                    "top_p".to_string(),
                    ToolParameter {
                        name: "top_p".to_string(),
                        param_type: "number".to_string(),
                        description: Some("Top-p sampling (default: 1.0)".to_string()),
                        required: Some(false),
                        default: Some(serde_json::json!(1.0)),
                        enum_values: None,
                    },
                );
                props.insert(
                    "stop".to_string(),
                    ToolParameter {
                        name: "stop".to_string(),
                        param_type: "array".to_string(),
                        description: Some("Stop sequences".to_string()),
                        required: Some(false),
                        default: None,
                        enum_values: None,
                    },
                );
                props
            },
            required: Some(vec!["messages".to_string()]),
        })
    }

    async fn execute(&self, input: &str, _ctx: &mut Context) -> Result<ToolResult, ToolError> {
        let chat_input: ChatCompletionInput = serde_json::from_str(input)
            .map_err(|e| ToolError::InvalidInput(format!("Invalid chat completion input: {}", e)))?;

        if chat_input.messages.is_empty() {
            return Err(ToolError::InvalidInput(
                "At least one message is required".to_string()
            ));
        }

        let response = self.complete(&chat_input).await?;
        Ok(ToolResult::success(Self::format_response(&response)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_chat_completion_tool_new() {
        let tool = ChatCompletionTool::new();
        assert_eq!(tool.name(), "chat_completion");
    }

    #[test]
    fn test_chat_completion_with_model() {
        let tool = ChatCompletionTool::with_model("claude-3-opus");
        assert_eq!(tool.default_model, "claude-3-opus");
    }

    #[test]
    fn test_estimate_tokens() {
        let tokens = ChatCompletionTool::estimate_tokens("Hello world");
        assert!(tokens > 0);
    }

    #[tokio::test]
    async fn test_complete() {
        let tool = ChatCompletionTool::new();
        let input = ChatCompletionInput {
            messages: vec![
                ChatMessage {
                    role: MessageRole::User,
                    content: "What is 2+2?".to_string(),
                },
            ],
            model: None,
            temperature: 0.7,
            max_tokens: 100,
            top_p: 1.0,
            stop: None,
        };

        let response = tool.complete(&input).await.unwrap();
        assert!(!response.content.is_empty());
        assert!(response.usage.total_tokens > 0);
    }

    #[test]
    fn test_chat_input_deserialize() {
        let json = r#"{
            "messages": [
                {"role": "system", "content": "You are helpful."},
                {"role": "user", "content": "Hello!"}
            ],
            "model": "gpt-4",
            "temperature": 0.5,
            "max_tokens": 500
        }"#;

        let input: ChatCompletionInput = serde_json::from_str(json).unwrap();
        assert_eq!(input.messages.len(), 2);
        assert_eq!(input.model, Some("gpt-4".to_string()));
        assert_eq!(input.temperature, 0.5);
    }

    #[test]
    fn test_format_response() {
        let response = ChatCompletionResponse {
            content: "Hello!".to_string(),
            model: "gpt-4".to_string(),
            usage: TokenUsage {
                prompt_tokens: 10,
                completion_tokens: 5,
                total_tokens: 15,
            },
        };

        let formatted = ChatCompletionTool::format_response(&response);
        assert!(formatted.contains("gpt-4"));
        assert!(formatted.contains("Hello!"));
        assert!(formatted.contains("15"));
    }
}
